#!/usr/bin/perl -w

# Copyright (C) 2014 Tim Sterne-Weiler
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"), 
# to deal in the Software without restriction, including without limitation 
# the rights to use, copy, modify, merge, publish, distribute, sublicense, 
# and/or sell copies of the Software, and to permit persons to whom the Software 
# is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in 
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF 
# CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE 
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

use strict;

use FindBin;
use lib "$FindBin::Bin/lib";
use FuncBasics qw(:all);

use Getopt::Long;
use Cwd qw(abs_path);

use constant DEFAULT_OUTDIR => 'vast_out';

our $EXIT_STATUS = 0;

# INITIALIZE
my $path = abs_path($0);
$0 =~ s/^.*\///;
$path =~ s/\/$0$//;

# COMMAND FLAG DEFAULTS
my $input;

my $cores = 1; # by Default

my $legacyFlag = 0; # Use old input and output... Not by default.
my $helpFlag = 0;
my $cleanFlag = 0;

my $outdir = undef;

my $subCommand = shift @ARGV or $helpFlag = 1;

my @args = @ARGV;

Getopt::Long::Configure("pass_through", "no_auto_abbrev");
GetOptions("help" => \$helpFlag,
			  "legacy" => \$legacyFlag,
			  "output=s" => \$outdir,
			  "clean" => \$cleanFlag);

if($helpFlag and 
	!defined($subCommand) or
   (($subCommand eq "align" or
	  $subCommand eq "combine" or
	  $subCommand eq "diff") ? 0 : 1)) {
  die "
Usage: $0 sub-commands [options]

[sub-commands]
	align
	combine
	diff

[global options]
	-h,--help	:	Print this message
	--output	:	Output directory (default vast_out)
	--legacy	:	Use old input/output styles
	--verbose	:	Print stderr

"
}

# Check if output directory option was specified --KH
# If not, set the default and add to @args
if (! defined $outdir) {
    $outdir = DEFAULT_OUTDIR;
    push @args, "--output=$outdir";
}

# this may need to be altered later --TSW
if($cleanFlag) {
  #system("rm -rf $outdir");
} else {
  unless($helpFlag or !defined($ARGV[0])) { 
    mkdir($outdir) unless (-e $outdir);
    #chdir($outdir);
  }
}

## Nuts and Bolts...
if($subCommand eq "align") {
  $EXIT_STATUS = system("$path/bin/RunDBS_1.pl @args");
} elsif($subCommand eq "combine") {
  $EXIT_STATUS = system("$path/bin/RunDBS_2.pl @args");
} elsif($subCommand eq "diff") {
  $EXIT_STATUS = system("$path/R/vastdiff.R @args");
}

exit $EXIT_STATUS;
