#!/usr/bin/perl -w

# Copyright (C) 2014 Tim Sterne-Weiler
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"), 
# to deal in the Software without restriction, including without limitation 
# the rights to use, copy, modify, merge, publish, distribute, sublicense, 
# and/or sell copies of the Software, and to permit persons to whom the Software 
# is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in 
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF 
# CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE 
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

use strict;

BEGIN {push @INC, 'lib'}
use FuncBasics qw(:all);

use Getopt::Long;
use Cwd qw(abs_path);

# INITIALIZE
my $path = abs_path($0);
$0 =~ s/^.*\///;
$path =~ s/\/$0$//;

# COMMAND FLAG DEFAULTS
my $input;

my $cores = 1; # by Default

my $legacyFlag = 0; # Use old input and output... Not by default.
my $helpFlag = 0;

my $output_dir; # Not defined by default

my $subCommand = shift @ARGV;

my @args = @ARGV;

Getopt::Long::Configure("pass_through");
GetOptions("help" => \$helpFlag,
			  "legacy" => \$legacyFlag,
			  "outputDir=s" => \$output_dir);


if($helpFlag and 
	!defined($subCommand) or
   (($subCommand eq "align" or
	  $subCommand eq "combine" or
	  $subCommand eq "diff") ? 0 : 1)) {
  die "
Usage: $0 sub-commands [options]

[sub-commands]
	align
	combine
	diff

[global options]
	-h,--help	:	Print this message
	--legacy	:	Use old input/output styles
	--verbose	:	Print stderr
"
}

if(defined($output_dir)) {
	chdir($output_dir);
}

if($subCommand eq "align") {
  system("$path/bin/RunDBS_1.pl @args");
} elsif($subCommand eq "combine") {
  system("$path/bin/RunDBS_2.pl @args");
} elsif($subCommand eq "diff") {
  system("$path/vastdiff/vastdiff.R @args");
}

1;
